### ISSUE TITLE
Can not get pass setting up the music folder, keep getting an error

### ISSUE THREAD

**Issue by BobWs** [Hyzual/docker-koel#17]
Hi,
I'm trying to setup the docker container on my Synology NAS and I keep getting an error when the setup arrives at setting up the music folder. If I leave it blank I'm getting the error if I specify the path I'm also getting the error. 

I have already check permissions and changed them to root but even that didn't help. 
Any idea how to solve this? Or what I'm I doing wrong in setting this up?

![Screen_Shot](https://user-images.githubusercontent.com/5485820/81541857-12da3080-9374-11ea-994c-1ded96a74f39.png)

**Comment by Hyzual** [comment]
Hi ! If you look closely the error is actually after "Now to front-end stuff". It does set the Media path correctly.

This error is "expected". Koel's setup script wants to build front-end assets such as Javascript, CSS and images. As part of building this docker image, those assets are already built in one of the stages. I don't think the "production" image should include development dependencies. That is why `yarn` and other tools required for this step are **not** installed in the final image. Thus, this step will always fail with this image, but it's "okay" as the assets are already built.

I wrote about it in the README: https://github.com/Hyzual/docker-koel#first-run
> /!\ koel:init will fail at the stage where it checks front-end assets. This is known and is due to the absence of node.js and yarn. koel's frontend assets are already built in this image so this step is not necessary.

**Comment by BobWs** [comment]
Yes I've read that and after this point I see the login webpage but when I enter the login credentials I cannot login

**Comment by BobWs** [comment]
At the moment I'm testing https://github.com/binhex/arch-koel and this one is working I'm able to login and see my music. This was much easier to install and configure.

**Comment by Hyzual** [comment]
I have had problems logging in too ever since I started using 0xcaff's docker image. I could never figure out where it came from, I never see any logs for errors. I assumed that was a bug in koel.
If you're telling me that logging in always works in arch-koel, then maybe it is due to some misconfiguration in this image. I don't have time to look deeply into it anyway.

Indeed, arch-koel does a lot of things, like automate the `koel:sync` part. I did not know about the `expect` command that is used.
Well, feel free to use arch-koel then :)

**Comment by BobWs** [comment]
Thanks for your answer. I’ve tested arch-koel and it was pretty easy to setup, it has mariadb built in so that’s a win and had no problem logging in and scan my test music folder. 
But honestly it’s not what I’m looking for. Koel doesn’t support e.g. mobile apps, and that is a must have for me. 
So for now I will stick with Navidrome
