### ISSUE TITLE
Raspberry Pi/Arm compatibility

### ISSUE THREAD

**Issue by Borkuz** [Hyzual/docker-koel#21]
I'm trying to run this container on my raspberry pi but keep getting an error and wont start.
`standard_init_linux.go:211: exec user process caused "exec format error"`

**Comment by Hyzual** [comment]
Hi, as far as I know this image is not compatible at all with Arm / Raspberry Pi. Everything uses i386 architecture.
I've never worked with Arm before so I don't think I can help you on that one :/

**Comment by Borkuz** [comment]
Ah to bad, thanks for the quick reply!

**Comment by Filius-Patris** [comment]
I'm just starting out on hosting docker-koel, but there are tons of guides about it, for [this one by arm](https://developer.arm.com/common-tasks/getting-started-with-docker/multi-architecture-images).

Basically it boils down to getting a fairly recent version of Docker (something about 19.03) and then using the new tool `buildx` to build and specifying `--platform`.

I won't have time the next 3 weeks or so, but if nobody will have it done by then, I'll try.

**Comment by Filius-Patris** [comment]
Ok, this is where I got stuck:
koel [relies on cypress](https://github.com/koel/koel/blob/master/package.json#L18) ([cypress project](https://github.com/cypress-io/cypress/)) for e2e frontend testing.
Ususally cypress installs itself by downloading a precompiled package. This package is however not available for arm architectures (see [this issue](https://github.com/cypress-io/cypress/issues/4478)).

If anyone has more experience with cypress specifically or npm packages generally, I'd love to get help about how to build cypress locally (even longer build times 🙄 ) and use this version of the package.
Additionally, if we manage to get reproducible builds for arm for cypress running, this might aid [the issue on cypress](https://github.com/cypress-io/cypress/issues/4478).
Guide for building cypress: https://github.com/cypress-io/cypress/blob/develop/DEPLOY.md#building-the-binary

**Comment by Hyzual** [comment]
Thanks for the explanation. What about using `CYPRESS_INSTALL_BINARY=0` to skip cypress installation altogether ? (see https://docs.cypress.io/guides/getting-started/installing-cypress.html#Skipping-installation)
Does it fail earlier at the "npm install" stage ?
After all, the purpose of docker-koel is to build a "production" docker image, we are not interested in running end to end tests.

**Comment by Filius-Patris** [comment]
Just as you're writing, I saw the 3198879 commit 😅 . Merged `master` and trying again...

**Comment by Filius-Patris** [comment]
It somehow still gets called ?
```
[linux/arm/v7 front-builder 4/4] RUN cd /tmp/koel/resources/assets &&   ...
2939. [4/4] Building fresh packages...
2950. info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
2950. error /tmp/koel/node_modules/cypress: Command failed.
2950. Exit code: 1
2950. Command: node index.js --exec install
2950. Arguments:  
2950. Directory: /tmp/koel/node_modules/cypress
2950. Output:
2950. Installing Cypress (version: 3.4.1)
2950.  
2950. [14:27:24]  Downloading Cypress     [started]
2950. [14:27:25]  Downloading Cypress     [failed]
2950. [14:27:25] → The Cypress App could not be downloaded.
2950.  
2950. Does your workplace require a proxy to be used to access the Internet? If so, you must configure the HTTP_PROXY environment variable before downloading Cypress. Read more: https://on.cypress.io/proxy-configuration
2950.  
2950. Otherwise, please check network connectivity and try again:
2950.  
2950. ----------
2950.  
2950. URL: https://download.cypress.io/desktop/3.4.1?platform=linux&arch=ia32
2950. Error: Failed downloading the Cypress binary.
2950. Response code: 404
2950. Response message: Not Found
2950.  
2950. ----------
2950.  
2950. Platform: linux (Raspbian - )
2950. Cypress Version: 3.4.1
2950. The Cypress App could not be downloaded.
2950.  
2950. Does your workplace require a proxy to be used to access the Internet? If so, you must configure the HTTP_PROXY environment variable before downloading Cypress. Read more: https://on.cypress.io/proxy-configuration
2950.  
2950. Otherwise, please check network connectivity and try again:
2950.  
2950. ----------
2950.  
2950. URL: https://download.cypress.io/desktop/3.4.1?platform=linux&arch=ia32
2950. Error: Failed downloading the Cypress binary.
2950. Response code: 404
2950. Response message: Not Found
2950.  
2950. ----------
2950.  
2950. Platform: linux (Raspbian - )
2950. Cypress Version: 3.4.1
ERROR: executor failed running [/bin/sh -c cd /tmp/koel/resources/assets &&     CYPRESS_INSTALL_BINARY=0 yarn install --non-interactive --network-timeout 100000 &&     cd /tmp/koel/ &&     yarn install --non-interactive --network-timeout 100000 &&     yarn run production --network-timeout 100000 &&     rm -rf /tmp/koel/node_modules       /tmp/koel/resources/assets]: buildkit-runc did not terminate successfully
```

https://github.com/Filius-Patris/docker-koel/runs/923389541?check_suite_focus=true#step:5:9470

**Comment by Filius-Patris** [comment]
@Borkuz Issue can be closed!

![Screenshot 2020-08-03 at 12 57 38](https://user-images.githubusercontent.com/37048904/89175945-ff142400-d588-11ea-8266-00ca188cf4d2.png)

**Comment by Borkuz** [comment]
Legend! Thanks!
