### ISSUE TITLE
sh: 1: yarn: not found

### ISSUE THREAD

**Issue by icofans** [Hyzual/docker-koel#59]
Attempting to install or upgrade Koel.
Remember, you can always install/upgrade manually following the guide here:
📙  https://koel.phanan.net/docs

App key exists -- skipping
JWT secret exists -- skipping
Migrating database
Data seeded -- skipping
Now to front-end stuff
├── Installing Node modules in resources/assets directory
sh: 1: yarn: not found
Oops! Koel installation or upgrade didn't finish successfully.
Please try again, or visit https://koel.phanan.net/docs for manual installation.
😥 Sorry for this. You deserve better.

**Comment by Hyzual** [comment]
Hi, thanks for reporting the error. Please note that it is known and can be ignored safely [as stated in the README](https://github.com/Hyzual/docker-koel#first-run): 

> /!\ koel:init will fail at the stage where it checks front-end assets. This is known and is due to the absence of node.js and yarn. koel's frontend assets are already built in this image so this step is not necessary.

It is a bit annoying though so I've opened an issue in koel/koel for it, you can follow it here: https://github.com/koel/koel/issues/1283

**Comment by Hyzual** [comment]
While browsing the code I've discovered that there is a `--no-assets` option that will skip this unnecessary step. Try the following:

```sh
docker exec -it koel php artisan koel:init --no-assets
```

The error should not appear and the command should succeed.

**Comment by naggie** [comment]
Unfortunately the `--no-assets` flag doesn't seem to exist:

![image](https://user-images.githubusercontent.com/208440/110831177-e479fa00-8291-11eb-895d-0e9bf2b0e5d9.png)


Using master as of today (260165365f612a1bf63087fceb2c66a01be27f4e)

Removing the flag and letting it fail seems to be OK, as per the readme though. Not ideal, but it's a workaround.

**Comment by Hyzual** [comment]
Strange, I cannot reproduce. The flag is correctly recognized. I've tried with `hyzual/koel:latest` image ID `eb29cb3624cb`. From your screenshot, it looks like there is no typo either... :confused: 

```sh
$ docker exec -it docker-koel_koel_1 php artisan koel:init --no-assets
Attempting to install or upgrade Koel.
Remember, you can always install/upgrade manually following the guide here:
📙  https://docs.koel.dev

App key exists -- skipping
Migrating database
Let's create the admin account.

 Your name:
 > admin

 Your email address:
 > admin@example.com

 Your desired password:
 > 

 Again, just to be sure:
 > 

Seeding initial data
The absolute path to your media directory. If this is skipped (left blank) now, you can set it later via the web interface.

 Media path [/music]:
 > 


🎆  Success! Koel can now be run from localhost with `php artisan serve`.
You can also scan for media with `php artisan koel:sync`.
Again, visit 📙 https://docs.koel.dev for the official documentation.
Feeling generous and want to support Koel's development? Check out https://github.com/users/phanan/sponsorship 🤗
Thanks for using Koel. You rock! 🤘
```

**Comment by naggie** [comment]
you're totally right -- sorry! 

Turns out I had and old image -- `docker-compose pull` fixed it. I had assumed docker would grab a labelled version or something.
