### ISSUE TITLE
No log dir existent

### ISSUE THREAD

**Issue by jondoe1337** [Hyzual/docker-koel#61]
Just tried to find the laravel.log and looked in the storage dir, but there is no log dir:

```
root@9b5be6bc99be:/var/www/html# ls storage/
app  dotenv-editor  framework  search-indexes
```

I'm using docker-compose as recommended.

**Comment by jondoe1337** [comment]
Oh okay, I guess it is created lazy - for example after you do a manual sync

**Comment by Hyzual** [comment]
Indeed, the log directory is created lazily and might not exist on new containers.
